### ISSUE TITLE
Can't find tulip package

### ISSUE THREAD

**Issue by devapi016** [friolero/self_aligned_reward_learning#1]
Greetings!
First of all congratulations to authors for paper acceptance.

I am trying to setup the environment based on packages and version mentioned in `README.md`
But I could not find the tulip package that is used in this repo. 

Hence I request you to, if it is present in the web, add install instructions to this tulip package or, if it is a custom package, make that package available.

Thanks in advance

**Comment by friolero** [comment]
closing as the tulip dependency was removed.
