### ISSUE TITLE
BUG：NameError: name 'lines' is not defined

### ISSUE THREAD

**Issue by yeshenpy** [friolero/self_aligned_reward_learning#2]
![image](https://github.com/user-attachments/assets/1d91e83d-1c3a-4056-be69-3a1a71c3855a)

**Comment by friolero** [comment]
Hi thanks for the issue. Yes the split line is missing and I just added back here:

https://github.com/friolero/self_aligned_reward_learning/blob/main/reward_learning/utils.py#L245
